/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateProductArgs {
  'openedDate' : [] | [Timestamp],
  'expiryDate' : Timestamp,
  'name' : string,
  'notes' : [] | [string],
  'category' : string,
  'photo' : [] | [string],
  'location' : string,
}
export interface Product {
  'id' : ProductId,
  'status' : string,
  'openedDate' : [] | [Timestamp],
  'expiryDate' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'notes' : [] | [string],
  'category' : string,
  'photo' : [] | [string],
  'location' : string,
}
export type ProductId = string;
export interface Reminder {
  'id' : ReminderId,
  'alertHours' : bigint,
  'createdAt' : Timestamp,
  'productId' : ProductId,
}
export type ReminderId = string;
export type Timestamp = bigint;
export interface UpdateProductArgs {
  'id' : ProductId,
  'openedDate' : [] | [Timestamp],
  'expiryDate' : Timestamp,
  'name' : string,
  'notes' : [] | [string],
  'category' : string,
  'photo' : [] | [string],
  'location' : string,
}
export interface _SERVICE {
  'addReminder' : ActorMethod<[ProductId, bigint], Reminder>,
  'createProduct' : ActorMethod<[CreateProductArgs], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteReminder' : ActorMethod<[ReminderId], boolean>,
  'getExpiredCount' : ActorMethod<[], bigint>,
  'getFreshCount' : ActorMethod<[], bigint>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getSoonCount' : ActorMethod<[], bigint>,
  'getTotalProducts' : ActorMethod<[], bigint>,
  'getWasteSaved' : ActorMethod<[], number>,
  'initSampleData' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<[UpdateProductArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];