/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const ReminderId = IDL.Text;
export const Timestamp = IDL.Int;
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'alertHours' : IDL.Int,
  'createdAt' : Timestamp,
  'productId' : ProductId,
});
export const CreateProductArgs = IDL.Record({
  'openedDate' : IDL.Opt(Timestamp),
  'expiryDate' : Timestamp,
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'status' : IDL.Text,
  'openedDate' : IDL.Opt(Timestamp),
  'expiryDate' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const UpdateProductArgs = IDL.Record({
  'id' : ProductId,
  'openedDate' : IDL.Opt(Timestamp),
  'expiryDate' : Timestamp,
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addReminder' : IDL.Func([ProductId, IDL.Int], [Reminder], []),
  'createProduct' : IDL.Func([CreateProductArgs], [Product], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
  'getExpiredCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getFreshCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getSoonCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalProducts' : IDL.Func([], [IDL.Nat], ['query']),
  'getWasteSaved' : IDL.Func([], [IDL.Float64], ['query']),
  'initSampleData' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func([UpdateProductArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const ReminderId = IDL.Text;
  const Timestamp = IDL.Int;
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'alertHours' : IDL.Int,
    'createdAt' : Timestamp,
    'productId' : ProductId,
  });
  const CreateProductArgs = IDL.Record({
    'openedDate' : IDL.Opt(Timestamp),
    'expiryDate' : Timestamp,
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'status' : IDL.Text,
    'openedDate' : IDL.Opt(Timestamp),
    'expiryDate' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const UpdateProductArgs = IDL.Record({
    'id' : ProductId,
    'openedDate' : IDL.Opt(Timestamp),
    'expiryDate' : Timestamp,
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addReminder' : IDL.Func([ProductId, IDL.Int], [Reminder], []),
    'createProduct' : IDL.Func([CreateProductArgs], [Product], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
    'getExpiredCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFreshCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getSoonCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalProducts' : IDL.Func([], [IDL.Nat], ['query']),
    'getWasteSaved' : IDL.Func([], [IDL.Float64], ['query']),
    'initSampleData' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func([UpdateProductArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };