/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateProductArgs {
    id: ProductId;
    openedDate?: Timestamp;
    expiryDate: Timestamp;
    name: string;
    notes?: string;
    category: string;
    photo?: string;
    location: string;
}
export type Timestamp = bigint;
export type ReminderId = string;
export interface Reminder {
    id: ReminderId;
    alertHours: bigint;
    createdAt: Timestamp;
    productId: ProductId;
}
export type ProductId = string;
export interface CreateProductArgs {
    openedDate?: Timestamp;
    expiryDate: Timestamp;
    name: string;
    notes?: string;
    category: string;
    photo?: string;
    location: string;
}
export interface Product {
    id: ProductId;
    status: string;
    openedDate?: Timestamp;
    expiryDate: Timestamp;
    name: string;
    createdAt: Timestamp;
    notes?: string;
    category: string;
    photo?: string;
    location: string;
}
export interface backendInterface {
    addReminder(productId: ProductId, alertHours: bigint): Promise<Reminder>;
    createProduct(args: CreateProductArgs): Promise<Product>;
    deleteProduct(id: ProductId): Promise<boolean>;
    deleteReminder(id: ReminderId): Promise<boolean>;
    getExpiredCount(): Promise<bigint>;
    getFreshCount(): Promise<bigint>;
    getProductById(id: ProductId): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getProductsByCategory(category: string): Promise<Array<Product>>;
    getReminders(): Promise<Array<Reminder>>;
    getSoonCount(): Promise<bigint>;
    getTotalProducts(): Promise<bigint>;
    getWasteSaved(): Promise<number>;
    initSampleData(): Promise<void>;
    updateProduct(args: UpdateProductArgs): Promise<boolean>;
}
import type { CreateProductArgs as _CreateProductArgs, Product as _Product, ProductId as _ProductId, Timestamp as _Timestamp, UpdateProductArgs as _UpdateProductArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReminder(arg0: ProductId, arg1: bigint): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0, arg1);
            return result;
        }
    }
    async createProduct(arg0: CreateProductArgs): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_CreateProductArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_CreateProductArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: ReminderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async getExpiredCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiredCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiredCount();
            return result;
        }
    }
    async getFreshCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreshCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreshCount();
            return result;
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getSoonCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoonCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoonCount();
            return result;
        }
    }
    async getTotalProducts(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalProducts();
            return result;
        }
    }
    async getWasteSaved(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWasteSaved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWasteSaved();
            return result;
        }
    }
    async initSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async updateProduct(arg0: UpdateProductArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_UpdateProductArgs_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_UpdateProductArgs_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Product_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    status: string;
    openedDate: [] | [_Timestamp];
    expiryDate: _Timestamp;
    name: string;
    createdAt: _Timestamp;
    notes: [] | [string];
    category: string;
    photo: [] | [string];
    location: string;
}): {
    id: ProductId;
    status: string;
    openedDate?: Timestamp;
    expiryDate: Timestamp;
    name: string;
    createdAt: Timestamp;
    notes?: string;
    category: string;
    photo?: string;
    location: string;
} {
    return {
        id: value.id,
        status: value.status,
        openedDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.openedDate)),
        expiryDate: value.expiryDate,
        name: value.name,
        createdAt: value.createdAt,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        category: value.category,
        photo: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.photo)),
        location: value.location
    };
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CreateProductArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductArgs): _CreateProductArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductArgs_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductArgs): _UpdateProductArgs {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    openedDate?: Timestamp;
    expiryDate: Timestamp;
    name: string;
    notes?: string;
    category: string;
    photo?: string;
    location: string;
}): {
    id: _ProductId;
    openedDate: [] | [_Timestamp];
    expiryDate: _Timestamp;
    name: string;
    notes: [] | [string];
    category: string;
    photo: [] | [string];
    location: string;
} {
    return {
        id: value.id,
        openedDate: value.openedDate ? candid_some(value.openedDate) : candid_none(),
        expiryDate: value.expiryDate,
        name: value.name,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: value.category,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        location: value.location
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    openedDate?: Timestamp;
    expiryDate: Timestamp;
    name: string;
    notes?: string;
    category: string;
    photo?: string;
    location: string;
}): {
    openedDate: [] | [_Timestamp];
    expiryDate: _Timestamp;
    name: string;
    notes: [] | [string];
    category: string;
    photo: [] | [string];
    location: string;
} {
    return {
        openedDate: value.openedDate ? candid_some(value.openedDate) : candid_none(),
        expiryDate: value.expiryDate,
        name: value.name,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: value.category,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        location: value.location
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
